Questionnaire/Questionnaire/urls.py
from django.urls import path
from . import views

app_name = 'Questionnaire'

urlpatterns = [
    # ex: /Questionnaire/
    path('', views.index, name='index'),
    # ex: /Questionnaire/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /Questionnaire/5/results/
    path('<int:question_id>/result/', views.results, name='result'),
    # ex: /Questionnaire/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Questionnaire/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Questionnaire/',include('Questionnaire.urls')),
    path('admin/', admin.site.urls),
]

Questionnaire/Questionnaire/models.py
from django.db import models
from django.utils import timezone

import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
class Choice (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

Questionnaire/Questionnaire/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from .models import Question, Choice
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5] 
    context = {
        'latest_question_list' : latest_question_list,
    }
    return render(request,'Questionnaire/index.html',context)

def detail(request, question_id): 
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'Questionnaire/detail.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'Questionnaire/results.html', {'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try: 
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'Questionnaire/detail.html',{
            'question':question,
            'error_message': "You didn't select a choice.",
        })    
    else:
        selected_choice.votes += 1
        selected_choice.save()
        
        return HttpResponseRedirect(reverse('Questionnaire: results', args=question_id,))

Questionnaire/Questionnaire/templates/Questionnaire/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Page</title>

</head>
<body>
    <h1>
        {{question.question_text}}
    </h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'Questionnaire:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        <br>
    {%endfor%}
        <input type="submit" value="Vote">
    </form>
</body>
</html>

Questionnaire/Questionnaire/templates/Questionnaire/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
    {%load static%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <!---URL 탬플릿 태그를 사용하여 하드코딩된 URL 지움 (향후 유지보수에 용이) -->
            <a href="{% url 'Questionnaire:detail' question.id %}">{{ question.question_text }}</a>    
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

Questionnaire/Questionnaire/templates/Questionnaire/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Page</title>

</head>
<body>
    <h1>
        {{question.question_text}}
    </h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'Questionnaire:detail' question.id %}">Vote Again?</a>
</body>
</html>